// Datos completos del caso de estudio DAILY App, extraídos íntegramente de portfolio-qa-ux.
const DAILY = {
  es: {
    title: "DAILY – App",
    subtitle: "Aplicación de gestión financiera multimoneda diseñada para centralizar cuentas, registrar transacciones y visualizar balances en tiempo real.",
    description: "DAILY es una aplicación personal que desarrollé para resolver mi propia necesidad de gestión financiera multimoneda. La uso activamente para mi control de gastos, y apliqué sobre ella un proceso completo de testing manual — diseño de casos de prueba, testing funcional, exploratorio y de casos límite — para asegurar su calidad antes y durante el uso diario.",
    objective: "Validar el correcto funcionamiento de los flujos principales de la aplicación, asegurando la consistencia de los balances financieros y una experiencia de usuario clara en dispositivos móviles.",
    platform: "PWA (Progressive Web App), publicada en Vercel, optimizada para Android e iOS.",
    scope: [
      "Autenticación (PIN / huella)",
      "CRUD de transacciones (gastos e ingresos)",
      "Gestión de cuentas y presupuestos",
      "Módulo de viajes y deudas",
      "Dashboard y gráficos",
      "Validaciones y manejo de errores",
      "Soporte multimoneda"
    ],
    strategy: [
      { name: "Functional Testing", description: "Validación de flujos críticos: transacciones, balances, presupuestos y deudas." },
      { name: "Exploratory Testing", description: "Uso diario real para detectar comportamientos inesperados en flujos secundarios." },
      { name: "UI Testing", description: "Visualización correcta de componentes, formularios y feedback en mobile." },
      { name: "Edge Case Testing", description: "Escenarios límite: montos vacíos, cero, datos incompletos en formularios." }
    ],
    scenariosDesc: "A partir de las funcionalidades principales de la aplicación se definieron diferentes escenarios de prueba para validar los flujos críticos del sistema.",
    scenarios: [
      { id: "TS-001", feature: "Autenticación", scenario: "Acceso mediante PIN o biometría", objective: "Validar autenticación correcta y manejo de intentos inválidos con feedback claro", priority: "Crítico" },
      { id: "TS-002", feature: "Cuentas", scenario: "Gestión de cuentas multimoneda", objective: "Verificar creación de cuentas y consistencia de datos entre monedas", priority: "Crítico" },
      { id: "TS-003", feature: "Transacciones", scenario: "Registro de transacciones", objective: "Validar impacto de ingresos y gastos en balances y vistas", priority: "Crítico" },
      { id: "TS-004", feature: "Multimoneda", scenario: "Totales por moneda", objective: "Verificar independencia de cálculos entre monedas", priority: "Crítico" },
      { id: "TS-005", feature: "Dashboard", scenario: "Representación visual de datos", objective: "Validar símbolos de moneda y consistencia visual", priority: "Grave" },
      { id: "TS-006", feature: "Viajes", scenario: "Gestión de viajes", objective: "Verificar asociación de gastos y actualización de progreso", priority: "Grave" },
      { id: "TS-007", feature: "Viajes", scenario: "Presupuesto de viaje", objective: "Validar comportamiento al superar límites y feedback UX", priority: "Crítico" },
      { id: "TS-008", feature: "Deudas", scenario: "Gestión de deudas", objective: "Validar registro y visualización correcta de deudas", priority: "Grave" },
      { id: "TS-009", feature: "Presupuestos", scenario: "Presupuesto mensual", objective: "Verificar cálculo de gasto acumulado y porcentaje", priority: "Grave" },
      { id: "TS-010", feature: "Validaciones", scenario: "Validaciones de inputs", objective: "Validar manejo de datos inválidos sin inconsistencias", priority: "Crítico" }
    ],
    casesDesc: "Cada caso de prueba está vinculado a su escenario correspondiente. Los estados reflejan los resultados obtenidos durante la ejecución. Hacé clic en una fila para ver el detalle completo.",
    cases: [
      { id: "TC-001", scenarioId: "TS-003", feature: "Registrar un nuevo gasto asociado a una cuenta", precondition: "Usuario autenticado. Cuenta en ARS activa con saldo > $0. Al menos una categoría disponible.", result: "El gasto se guarda correctamente. El balance pasa de $2000 a $1500 y se refleja de forma consistente en dashboard y vista de transacciones.", status: "fail", bug: "BUG-002", tipo: "Funcional",
        steps: ["Ir a Transacciones → Nueva transacción", "Seleccionar tipo: Gasto", "Seleccionar cuenta ARS", "Ingresar monto: $500", "Seleccionar categoría: Comida", "Guardar", "Verificar balance en la cuenta", "Verificar dashboard"],
        testData: "Cuenta: ARS, saldo inicial: $2000 / Monto gasto: $500 / Categoría: Comida" },
      { id: "TC-002", scenarioId: "TS-003", feature: "Registrar un ingreso y verificar impacto en balance", precondition: "Usuario autenticado. Cuenta en ARS activa.", result: "El ingreso se registra correctamente. El balance pasa de $1000 a $4000 y se refleja en todas las vistas.", status: "pass", tipo: "Funcional",
        steps: ["Ir a Transacciones → Nueva transacción", "Seleccionar tipo: Ingreso", "Seleccionar cuenta ARS", "Ingresar monto: $3000", "Guardar", "Verificar balance", "Verificar dashboard y transacciones"],
        testData: "Cuenta: ARS, saldo inicial: $1000 / Monto ingreso: $3000" },
      { id: "TC-003", scenarioId: "TS-002", feature: "Crear nueva cuenta en moneda EUR", precondition: "Usuario autenticado. No existe cuenta en EUR previamente.", result: "La cuenta se crea correctamente con símbolo € y no genera cambios en otras cuentas.", status: "pass", tipo: "Funcional / Integración",
        steps: ["Ir a Cuentas → Nueva cuenta", "Ingresar nombre: “Cuenta Europa”", "Seleccionar moneda: EUR", "Guardar", "Verificar listado", "Verificar que no afecta otras cuentas"],
        testData: "Nombre: Cuenta Europa / Moneda: EUR / Saldo inicial: €0" },
      { id: "TC-004", scenarioId: "TS-004", feature: "Gasto en USD no afecta totales de EUR y ARS", precondition: "Usuario autenticado. Cuentas activas en USD, EUR y ARS con saldo.", result: "Solo USD se actualiza. EUR y ARS permanecen sin cambios. No hay inconsistencias.", status: "pass", tipo: "Integración / Multimoneda",
        steps: ["Ir a Transacciones", "Seleccionar cuenta USD", "Registrar gasto $50", "Guardar", "Ir a Dashboard", "Verificar totales por moneda"],
        testData: "USD: $200 → $150 / EUR: €150 / ARS: $5000" },
      { id: "TC-005", scenarioId: "TS-005", feature: "Verificar representación del símbolo EUR en el sistema", precondition: "Usuario autenticado. Cuenta EUR activa.", result: "El sistema muestra correctamente el símbolo € en todos los componentes (dashboard, gráficos y vistas).", status: "fail", bug: "BUG-004", tipo: "UX / Visual",
        steps: ["Ir a Dashboard", "Ver cuenta EUR", "Verificar símbolo en gráficos, lista y detalle"],
        testData: "Cuenta EUR: €200" },
      { id: "TC-006", scenarioId: "TS-006", feature: "Gasto asociado a viaje y actualización de progreso", precondition: "Usuario autenticado. Viaje activo con presupuesto y gasto previo.", result: "El gasto se asocia correctamente. El total pasa a €250 (50%) y se refleja en todos los módulos.", status: "fail", bug: "BUG-003", tipo: "Funcional / Integración",
        steps: ["Ir a Viajes", "Seleccionar viaje", "Registrar gasto €50", "Guardar", "Verificar progreso", "Verificar cuenta y dashboard"],
        testData: "Presupuesto: €500 / Gasto previo: €200" },
      { id: "TC-007", scenarioId: "TS-007", feature: "Superar presupuesto de viaje y validar feedback", precondition: "Usuario autenticado. Viaje con presupuesto casi alcanzado.", result: "El sistema muestra alerta al superar el presupuesto. Se refleja correctamente ($1050) y se indica visualmente.", status: "fail", bug: "BUG-006", tipo: "Funcional / UX / Edge",
        steps: ["Ir a Viajes", "Agregar gasto $100", "Guardar", "Verificar notificación", "Verificar barra y valores"],
        testData: "Presupuesto: $1000 / Gasto previo: $950" },
      { id: "TC-008", scenarioId: "TS-008", feature: "Registrar deuda “Me deben”", precondition: "Usuario autenticado. Sin deudas previas.", result: "La deuda se registra correctamente en la vista “Me deben” y no aparece en “Debo”.", status: "pass", tipo: "Funcional",
        steps: ["Ir a Deudas", "Nueva deuda", "Seleccionar “Me deben”", "Ingresar datos", "Guardar", "Verificar vista"],
        testData: "Nombre: Juan / Monto: $300" },
      { id: "TC-009", scenarioId: "TS-009", feature: "Cálculo de porcentaje de presupuesto mensual", precondition: "Usuario autenticado. Presupuesto activo con gastos.", result: "El sistema calcula correctamente el porcentaje (90%) y muestra proximidad al límite.", status: "pass", tipo: "Funcional / Cálculo",
        steps: ["Ir a Presupuestos", "Ver gasto actual", "Agregar gasto", "Verificar porcentaje"],
        testData: "Presupuesto: $5000 / Gasto: $3500 → $4500" },
      { id: "TC-010", scenarioId: "TS-010", feature: "Validación de campo monto vacío", precondition: "Usuario autenticado. Cuenta activa.", result: "El sistema bloquea la acción, muestra error y no guarda datos ni modifica balances.", status: "fail", bug: "BUG-005", tipo: "Validación / Negativo",
        steps: ["Ir a Transacciones", "Dejar monto vacío", "Intentar guardar"],
        testData: "Monto vacío" },
      { id: "TC-011", scenarioId: "TS-001", feature: "Validar autenticación con PIN incorrecto", precondition: "Usuario registrado con PIN configurado", result: "El sistema bloquea acceso y muestra mensaje claro de error sin permitir ingreso.", status: "fail", bug: "BUG-001", tipo: "Seguridad / Validación",
        steps: ["Abrir app", "Ingresar PIN incorrecto", "Confirmar"],
        testData: "PIN incorrecto" }
    ],
    bugsDescription: "Se identificaron y documentaron los siguientes defectos críticos durante la ejecución de las pruebas.",
    bugs: [
      { id: "BUG-001", title: "Falta de feedback al ingresar PIN incorrecto", severity: "Medium", type: "Autenticación", testCaseId: "TS-001 / TC-011",
        steps: ["Abrir la aplicación", "Ingresar un PIN incorrecto (1234)"],
        expected: "El sistema bloquea el acceso y muestra un mensaje claro indicando que el PIN es incorrecto.", actual: "El acceso es bloqueado pero no se muestra ningún mensaje de error.", evidence: "../../img/daily/BUG-001-PIN-incorrecto.mp4" },
      { id: "BUG-002", title: "Desincronización temporal de datos en dashboard", severity: "Low", type: "Dashboard", testCaseId: "TS-003 / TC-001",
        steps: ["Registrar un nuevo gasto", "Ir inmediatamente al dashboard", "Verificar valores mostrados"],
        expected: "El dashboard refleja inmediatamente el cambio en los balances.", actual: "Algunos valores tardan en actualizarse hasta refrescar la vista.", evidence: "../../img/daily/daily-mockup-funciones.jpeg" },
      { id: "BUG-003", title: "No se pueden editar gastos desde la vista de viajes", severity: "High", type: "Viajes", testCaseId: "TS-006 / TC-006",
        steps: ["Ir a Viajes", "Seleccionar un viaje", "Intentar editar un gasto registrado"],
        expected: "El usuario puede editar el gasto desde la vista de viajes.", actual: "No es posible editar el gasto desde esa vista.", evidence: "../../img/daily/BUG-003 - Viajes-Editar gatsos.jpeg" },
      { id: "BUG-004", title: "Símbolo de moneda incorrecto en dashboard (EUR)", severity: "Medium", type: "Visual / Dashboard", testCaseId: "TS-005 / TC-005",
        steps: ["Ir al dashboard", "Visualizar cuenta en EUR", "Revisar símbolo mostrado"],
        expected: "El sistema muestra el símbolo “€” correctamente.", actual: "El sistema muestra “$” en lugar de “€” en algunos componentes.", evidence: "../../img/daily/BUG-004-Error moneda.jpeg" },
      { id: "BUG-005", title: "Se permite guardar transacción con monto de 0", severity: "High", type: "Validación", testCaseId: "TS-010 / TC-010",
        steps: ["Ir a nueva transacción", "Ingresar monto 0", "Guardar"],
        expected: "El sistema bloquea la acción y muestra mensaje de error.", actual: "La transacción se guarda con monto 0 generando un comportamiento inconsistente.", evidence: "../../img/daily/BUG-005-gasto-monto-0.jpeg" },
      { id: "BUG-006", title: "Falta de alerta clara al superar presupuesto de viaje", severity: "Medium", type: "UX / Alertas", testCaseId: "TS-007 / TC-007",
        steps: ["Registrar gasto que supere el presupuesto", "Confirmar operación", "Verificar feedback del sistema"],
        expected: "El sistema muestra una alerta clara indicando que se superó el presupuesto.", actual: "El sistema permite la operación pero no muestra un feedback claro o visible; la barra de progreso carga pero no alerta al usuario.", evidence: "../../img/daily/BUG-006-Viajes-presupuesto-alerta.jpeg" }
    ],
    uxImprovements: [
      "Feedback y estado del sistema: al completar una operación (registrar gasto, crear cuenta, saldar deuda), la app no confirma visualmente que la acción se realizó. Un mensaje breve o micro-animación reduciría la incertidumbre del usuario y prevendría registros duplicados.",
      "Perfiles de usuario: la app actualmente no diferencia usuarios. Incorporar un perfil básico permitiría personalizar preferencias (moneda por defecto, categorías frecuentes) y abriría la puerta a funcionalidades multiusuario.",
      "Creación de cuentas personalizadas: permitir crear cuentas o billeteras virtuales con nombre, moneda e ícono propios haría la app adaptable a distintos contextos financieros.",
      "Transferencias entre cuentas: hoy mover fondos entre cuentas requiere registrar un egreso en una y un ingreso en otra manualmente. Una transferencia directa reduciría errores.",
      "Filtrado inteligente por moneda: al registrar una transacción, mostrar solo las cuentas que coinciden con la moneda seleccionada evitaría errores de asignación.",
      "Autenticación mejorada: incorporar inicio de sesión con Google y autenticación biométrica simplificaría el onboarding y reforzaría la seguridad del acceso."
    ],
    labels: {
      description: "DESCRIPCIÓN", objective: "OBJETIVO", platform: "PLATAFORMA", scope: "ALCANCE DEL TESTING",
      strategy: "ESTRATEGIA DE TESTING", scenarios: "ESCENARIOS DE PRUEBA", cases: "CASOS DE PRUEBA", bugs: "BUGS DETECTADOS", ux: "MEJORAS DE UX",
      thId: "ID", thFeature: "Funcionalidad", thScenario: "Escenario", thObjective: "Objetivo", thPriority: "Prioridad", thResult: "Resultado", thStatus: "Estado",
      critical: "Crítico", pass: "Pasa", fail: "Falla", expected: "Esperado", actual: "Obtenido", evidence: "Ver evidencia", contact: "Contáctame",
      precondition: "Precondición", steps: "Pasos para reproducir", testData: "Datos de prueba", detail: "Ver detalle", collapse: "Ocultar detalle"
    }
  },
  en: {
    title: "DAILY – App",
    subtitle: "Multi-currency financial management application designed to centralize accounts, record transactions, and visualize balances in real time.",
    description: "DAILY is a personal application I developed to solve my own need for multi-currency financial management. I actively use it to track my own expenses, and I applied a full manual testing process to it — test case design, functional, exploratory, and edge-case testing — to ensure its quality before and during daily use.",
    objective: "Validate the correct functioning of the application's main flows, ensuring financial balance consistency and a clear user experience on mobile devices.",
    platform: "PWA (Progressive Web App), published on Vercel, optimized for Android and iOS.",
    scope: [
      "Authentication (PIN / fingerprint)",
      "Transaction CRUD (expenses and income)",
      "Account and budget management",
      "Travel and debt module",
      "Dashboard and charts",
      "Validations and error handling",
      "Multi-currency support"
    ],
    strategy: [
      { name: "Functional Testing", description: "Validation of critical flows: transactions, balances, budgets, and debts." },
      { name: "Exploratory Testing", description: "Real daily use to detect unexpected behaviors in secondary flows." },
      { name: "UI Testing", description: "Correct visualization of components, forms, and feedback on mobile." },
      { name: "Edge Case Testing", description: "Limit scenarios: empty amounts, zero, incomplete data in forms." }
    ],
    scenariosDesc: "Based on the main functionalities of the application, different test scenarios were defined to validate the critical flows of the system.",
    scenarios: [
      { id: "TS-001", feature: "Authentication", scenario: "Access via PIN or biometrics", objective: "Validate correct authentication and handling of invalid attempts with clear feedback", priority: "Critical" },
      { id: "TS-002", feature: "Accounts", scenario: "Multi-currency account management", objective: "Verify account creation and data consistency between currencies", priority: "Critical" },
      { id: "TS-003", feature: "Transactions", scenario: "Transaction recording", objective: "Validate impact of income and expenses on balances and views", priority: "Critical" },
      { id: "TS-004", feature: "Multi-currency", scenario: "Totals by currency", objective: "Verify independence of calculations between currencies", priority: "Critical" },
      { id: "TS-005", feature: "Dashboard", scenario: "Visual data representation", objective: "Validate currency symbols and visual consistency", priority: "Serious" },
      { id: "TS-006", feature: "Travels", scenario: "Travel management", objective: "Verify expense association and progress update", priority: "Serious" },
      { id: "TS-007", feature: "Travels", scenario: "Trip budget", objective: "Validate behavior when exceeding limits and UX feedback", priority: "Critical" },
      { id: "TS-008", feature: "Debts", scenario: "Debt management", objective: "Validate correct recording and visualization of debts", priority: "Serious" },
      { id: "TS-009", feature: "Budgets", scenario: "Monthly budget", objective: "Verify calculation of accumulated spending and percentage", priority: "Serious" },
      { id: "TS-010", feature: "Validations", scenario: "Input validations", objective: "Validate handling of invalid data without inconsistencies", priority: "Critical" }
    ],
    casesDesc: "Each test case is linked to its corresponding scenario. The statuses reflect the results obtained during execution. Click a row to see the full detail.",
    cases: [
      { id: "TC-001", scenarioId: "TS-003", feature: "Register a new expense associated with an account", precondition: "Authenticated user. Active ARS account with balance > $0. At least one category available.", result: "Expense saved correctly. Balance goes from $2000 to $1500 and is reflected consistently in dashboard and transactions.", status: "fail", bug: "BUG-002", tipo: "Functional",
        steps: ["Go to Transactions → New transaction", "Select type: Expense", "Select ARS account", "Enter amount: $500", "Select category: Food", "Save", "Verify balance", "Verify dashboard"],
        testData: "Account: ARS, initial balance: $2000 / Expense: $500 / Category: Food" },
      { id: "TC-002", scenarioId: "TS-003", feature: "Register an income and verify balance impact", precondition: "Authenticated user. Active ARS account.", result: "Income registered correctly. Balance goes from $1000 to $4000 and is reflected in all views.", status: "pass", tipo: "Functional",
        steps: ["Go to Transactions → New transaction", "Select type: Income", "Select ARS account", "Enter amount: $3000", "Save", "Verify balance", "Verify dashboard and transactions"],
        testData: "Account: ARS, initial balance: $1000 / Income: $3000" },
      { id: "TC-003", scenarioId: "TS-002", feature: "Create new account in EUR", precondition: "Authenticated user. No previous EUR account.", result: "Account created correctly with € symbol and no impact on other accounts.", status: "pass", tipo: "Functional / Integration",
        steps: ["Go to Accounts → New account", "Enter name: “Europe Account”", "Select currency: EUR", "Save", "Verify list", "Verify other accounts remain unchanged"],
        testData: "Name: Europe Account / Currency: EUR / Initial balance: €0" },
      { id: "TC-004", scenarioId: "TS-004", feature: "USD expense does not affect EUR and ARS totals", precondition: "Authenticated user. Active accounts in USD, EUR and ARS with balance.", result: "Only USD total updates. EUR and ARS remain unchanged. No inconsistencies.", status: "pass", tipo: "Integration / Multi-currency",
        steps: ["Go to Transactions", "Select USD account", "Register $50 expense", "Save", "Check dashboard", "Verify all currency totals"],
        testData: "USD: $200 → $150 / EUR: €150 / ARS: $5000" },
      { id: "TC-005", scenarioId: "TS-005", feature: "Verify EUR symbol representation in the system", precondition: "Authenticated user. Active EUR account.", result: "System correctly shows € symbol in all components (dashboard, charts and views).", status: "fail", bug: "BUG-004", tipo: "UX / Visual",
        steps: ["Go to Dashboard", "View EUR account", "Verify symbol in charts, list and detail"],
        testData: "EUR account: €200" },
      { id: "TC-006", scenarioId: "TS-006", feature: "Expense associated with trip and progress update", precondition: "Authenticated user. Active trip with budget and previous expense.", result: "Expense correctly linked. Total updates to €250 (50%) and reflects in all modules.", status: "fail", bug: "BUG-003", tipo: "Functional / Integration",
        steps: ["Go to Trips", "Select trip", "Register €50 expense", "Save", "Verify progress", "Verify account and dashboard"],
        testData: "Budget: €500 / Prev. expense: €200" },
      { id: "TC-007", scenarioId: "TS-007", feature: "Exceed trip budget and validate feedback", precondition: "Authenticated user. Trip with budget nearly reached.", result: "System shows alert when exceeding budget. Reflected correctly ($1050) and visually indicated.", status: "fail", bug: "BUG-006", tipo: "Functional / UX / Edge",
        steps: ["Go to Trips", "Add $100 expense", "Save", "Verify notification", "Verify bar and values"],
        testData: "Budget: $1000 / Prev. expense: $950" },
      { id: "TC-008", scenarioId: "TS-008", feature: "Register “They Owe Me” debt", precondition: "Authenticated user. No previous debts.", result: "Debt registered correctly in “They Owe Me” view and does not appear in “I Owe”.", status: "pass", tipo: "Functional",
        steps: ["Go to Debts", "New debt", "Select “They Owe Me”", "Enter data", "Save", "Verify view"],
        testData: "Name: Juan / Amount: $300" },
      { id: "TC-009", scenarioId: "TS-009", feature: "Monthly budget usage percentage calculation", precondition: "Authenticated user. Active budget with expenses.", result: "System correctly calculates percentage (90%) and shows proximity to limit.", status: "pass", tipo: "Functional / Calculation",
        steps: ["Go to Budgets", "Check current expense", "Add expense", "Verify percentage"],
        testData: "Budget: $5000 / Expense: $3500 → $4500" },
      { id: "TC-010", scenarioId: "TS-010", feature: "Empty amount field validation", precondition: "Authenticated user. Active account.", result: "System blocks action, shows error and does not save data or modify balances.", status: "fail", bug: "BUG-005", tipo: "Validation / Negative",
        steps: ["Go to Transactions", "Leave amount empty", "Attempt to save"],
        testData: "Empty amount" },
      { id: "TC-011", scenarioId: "TS-001", feature: "Validate authentication with incorrect PIN", precondition: "Registered user with PIN configured", result: "System blocks access and shows clear error message without allowing entry.", status: "fail", bug: "BUG-001", tipo: "Security / Validation",
        steps: ["Open app", "Enter incorrect PIN", "Confirm"],
        testData: "Incorrect PIN" }
    ],
    bugsDescription: "The following critical defects were identified and documented during the testing execution.",
    bugs: [
      { id: "BUG-001", title: "Missing feedback when entering incorrect PIN", severity: "Medium", type: "Authentication", testCaseId: "TS-001 / TC-011",
        steps: ["Open the application", "Enter an incorrect PIN", "Confirm access"],
        expected: "The system blocks access and shows a clear message indicating that the PIN is incorrect.", actual: "Access is blocked but no error message is displayed.", evidence: "../../img/daily/BUG-001-PIN-incorrecto.mp4" },
      { id: "BUG-002", title: "Temporal data desynchronization on dashboard", severity: "Low", type: "Dashboard", testCaseId: "TS-003 / TC-001",
        steps: ["Register a new expense", "Go immediately to the dashboard", "Verify values shown"],
        expected: "The dashboard immediately reflects the change in balances.", actual: "Some values take time to update until the view is manually refreshed.", evidence: "../../img/daily/daily-mockup-funciones.jpeg" },
      { id: "BUG-003", title: "Expenses cannot be edited from trip view", severity: "High", type: "Travels", testCaseId: "TS-006 / TC-006",
        steps: ["Go to Travels", "Select a trip", "Attempt to edit a registered expense"],
        expected: "The user can edit the expense from the trip view.", actual: "It is not possible to edit the expense from that view.", evidence: "../../img/daily/BUG-003 - Viajes-Editar gatsos.jpeg" },
      { id: "BUG-004", title: "Incorrect currency symbol on dashboard (EUR)", severity: "Medium", type: "Visual / Dashboard", testCaseId: "TS-005 / TC-005",
        steps: ["Go to dashboard", "View EUR account", "Review symbol shown"],
        expected: "The system displays the “€” symbol correctly.", actual: "The system displays “$” instead of “€” in some components.", evidence: "../../img/daily/BUG-004-Error moneda.jpeg" },
      { id: "BUG-005", title: "Saving transaction with empty amount is allowed", severity: "High", type: "Validation", testCaseId: "TS-010 / TC-010",
        steps: ["Go to new transaction", "Leave amount field empty", "Attempt to save"],
        expected: "The system blocks the action and shows an error message.", actual: "The transaction is saved without an amount or generates inconsistent behavior.", evidence: "../../img/daily/BUG-005-gasto-monto-0.jpeg" },
      { id: "BUG-006", title: "Missing clear alert when exceeding trip budget", severity: "Medium", type: "UX / Alerts", testCaseId: "TS-007 / TC-007",
        steps: ["Register expense that exceeds the budget", "Confirm operation", "Verify system feedback"],
        expected: "The system shows a clear alert indicating that the budget has been exceeded.", actual: "The system allows the operation but does not show clear or visible feedback.", evidence: "../../img/daily/BUG-006-Viajes-presupuesto-alerta.jpeg" }
    ],
    uxImprovements: [
      "Feedback and system status: when completing an operation (registering an expense, creating an account, settling a debt), the app does not visually confirm that the action was performed. A brief message or micro-animation would reduce user uncertainty and prevent duplicate registrations.",
      "User profiles: the app currently does not differentiate between users. Incorporating a basic profile would allow personalizing preferences and open the door to multi-user functionalities in the future.",
      "Custom account creation: allowing the user to create accounts or virtual wallets with their own name, currency, and icon would make the app adaptable to different financial contexts.",
      "Transfers between accounts: today, moving funds between accounts requires manually registering an expense in one and an income in another. A direct transfer functionality would reduce errors.",
      "Smart filtering by currency: showing only the accounts that match the selected currency would avoid assignment errors and make the flow faster.",
      "Improved authentication: incorporating Google login and biometric authentication would simplify onboarding and reinforce access security."
    ],
    labels: {
      description: "DESCRIPTION", objective: "OBJECTIVE", platform: "PLATFORM", scope: "TESTING SCOPE",
      strategy: "TESTING STRATEGY", scenarios: "TEST SCENARIOS", cases: "TEST CASES", bugs: "BUG REPORTS", ux: "UX IMPROVEMENTS",
      thId: "ID", thFeature: "Feature", thScenario: "Scenario", thObjective: "Objective", thPriority: "Priority", thResult: "Result", thStatus: "Status",
      critical: "Critical", pass: "Pass", fail: "Fail", expected: "Expected", actual: "Actual", evidence: "View evidence", contact: "Contact me",
      precondition: "Precondition", steps: "Steps to reproduce", testData: "Test data", detail: "View detail", collapse: "Hide detail"
    }
  }
};
