// Datos completos del caso de estudio UX & Accesibilidad — Ryanair, extraídos íntegramente de portfolio-qa-ux.
const RYANAIR = {
  es: {
    title: "UX & Accesibilidad — Ryanair",
    subtitle: "Análisis de usabilidad y accesibilidad sobre el sitio web de Ryanair.es",
    description: "Auditoría de UX y accesibilidad sobre el sitio web de Ryanair, evaluando tres páginas críticas del flujo de reserva: home, resultados de vuelos y proceso de checkout. El análisis combinó evaluación heurística basada en las 10 heurísticas de Nielsen con pruebas automatizadas de accesibilidad mediante Axe DevTools bajo el estándar WCAG 2.1 AA.",
    objective: "Identificar barreras de accesibilidad, problemas de usabilidad y oportunidades de mejora en el flujo principal de reserva de vuelos, con foco en el impacto real sobre el usuario.",
    platform: "Web Desktop y Mobile",
    stats: {
      title: "INCIDENCIAS DETECTADAS",
      headers: ["Página", "Total", "Críticos", "Graves", "Moderados"],
      rows: [
        ["Home", "34", "0", "9", "24"],
        ["Resultados de vuelos", "20", "0", "2", "18"],
        ["Checkout - Equipaje", "38", "12", "5", "21"],
        ["Total", "92", "12", "16", "63"]
      ]
    },
    strategy: [
      { name: "Evaluación Heurística", description: "10 heurísticas de Nielsen sobre búsqueda, selección de vuelo y checkout." },
      { name: "Accesibilidad", description: "Escaneo con Axe DevTools (WCAG 2.1 AA) en las tres páginas críticas del flujo." },
      { name: "Testing Exploratorio", description: "Navegación libre para detectar comportamientos no cubiertos por escaneos." },
      { name: "Testing Funcional", description: "Validación end-to-end: búsqueda → vuelo → equipaje, verificando consistencia." }
    ],
    scenariosDesc: "Se definieron 14 escenarios de prueba cubriendo accesibilidad, teclado, estructura semántica, localización, usabilidad y funcionalidad.",
    scenarios: [
      { id: "TS-001", feature: "Accesibilidad", scenario: "Escaneo Axe DevTools en home", objective: "Detectar incidencias WCAG 2.1 AA en la página principal", priority: "Crítico" },
      { id: "TS-002", feature: "Accesibilidad", scenario: "Escaneo Axe DevTools en checkout", objective: "Detectar incidencias WCAG 2.1 AA en el flujo de pago", priority: "Crítico" },
      { id: "TS-003", feature: "Keyboard", scenario: "Navegación con Tab en home", objective: "Verificar visibilidad del foco y orden lógico de tabulación", priority: "Crítico" },
      { id: "TS-004", feature: "Keyboard", scenario: "Navegación con Tab en resultados y checkout", objective: "Verificar que el foco es visible y funcional en todo el flujo", priority: "Crítico" },
      { id: "TS-005", feature: "Keyboard", scenario: "Comportamiento del modal de login con teclado", objective: "Verificar cierre con Escape y retorno de foco", priority: "Crítico" },
      { id: "TS-006", feature: "Estructura", scenario: "Headings y landmarks en home, resultados y checkout", objective: "Verificar jerarquía H1–H6 y presencia de landmark <main>", priority: "Crítico" },
      { id: "TS-007", feature: "Localización", scenario: "Idioma del video de asistencia especial", objective: "Verificar que el video se muestra en el idioma de la interfaz", priority: "Alto" },
      { id: "TS-008", feature: "Localización", scenario: "Idioma del menú de navegación", objective: "Verificar traducción completa del menú", priority: "Alto" },
      { id: "TS-009", feature: "Usabilidad", scenario: "Flujo de selección de origen y destino", objective: "Verificar que el buscador guía claramente al usuario", priority: "Alto" },
      { id: "TS-010", feature: "Usabilidad", scenario: "Consistencia de contenido en la home", objective: "Verificar ausencia de secciones duplicadas", priority: "Medio" },
      { id: "TS-011", feature: "Funcional", scenario: "Carga y elementos principales de la home", objective: "Validar que logo, buscador y menú son interactuables", priority: "Crítico" },
      { id: "TS-012", feature: "Funcional", scenario: "Buscador de vuelos — selección de fechas", objective: "Validar calendario de ida y vuelta", priority: "Crítico" },
      { id: "TS-013", feature: "Funcional", scenario: "Menú principal — despliegue y navegación", objective: "Validar que el menú 'Planear' se despliega correctamente", priority: "Alto" },
      { id: "TS-014", feature: "Funcional", scenario: "Resultados de búsqueda de vuelos", objective: "Validar que se muestran vuelos con precios y filtros", priority: "Crítico" }
    ],
    casesDesc: "Cada caso de prueba está vinculado a su escenario correspondiente. Hacé clic en una fila para ver el detalle completo.",
    cases: [
      { id: "TC-001", feature: "Ejecutar Axe DevTools en home bajo WCAG 2.1 AA", precondition: "Chrome actualizado. Axe DevTools 4.11.1 instalado. Home cargada sin caché.", result: "0 incidencias críticas o graves bajo WCAG 2.1 AA.", status: "fail", bug: "BUG-001",
        steps: ["Abrir ryanair.com/es/es", "Esperar carga completa", "Abrir Axe DevTools → 'Visión general'", "Clic en 'Volver a ejecutar el escaneo'", "Revisar panel de resultados — filtrar por Grave y Moderado"], testData: "Chrome 120+ / Axe DevTools 4.11.1 / WCAG 2.1 AA activado" },
      { id: "TC-002", feature: "Abrir modal de login y cerrar con Escape", precondition: "Chrome. Home cargada. Sin sesión iniciada.", result: "El modal se cierra al presionar Escape y el foco retorna al botón disparador (WCAG 2.1 SC 2.4.3).", status: "fail", bug: "BUG-011",
        steps: ["Ir a home de Ryanair", "Clic en 'Iniciar sesión'", "Verificar apertura del modal", "Presionar Escape", "Verificar cierre y retorno de foco"], testData: "Chrome / Sesión no iniciada / Navegación solo teclado" },
      { id: "TC-003", feature: "Validar contraste de textos, botones y enlaces en home", precondition: "Chrome. Axe DevTools instalado. Home cargada.", result: "Todos los textos cumplen ratio mínimo 4.5:1. Enlaces distinguibles sin depender solo del color.", status: "fail", bug: "BUG-002 / BUG-010",
        steps: ["Ejecutar Axe DevTools en home", "Filtrar por 'color-contrast' y 'link-in-text-block'", "Identificar elementos en fallo", "Verificar botón 'Buscar' con Color Picker", "Verificar ratio con WebAIM Contrast Checker"], testData: "Chrome / Axe DevTools / DevTools Color Picker" },
      { id: "TC-004", feature: "Verificar orden de tabulación en home", precondition: "Chrome sin extensiones que modifiquen CSS. Home cargada.", result: "El foco sigue orden lógico y predecible con outline visible en todos los elementos.", status: "fail", bug: "BUG-012",
        steps: ["Presionar Tab desde la barra de URL", "Documentar orden de foco", "Verificar outline visible en cada paso", "Verificar orden lógico header → buscador → contenido → footer"], testData: "Chrome / CSS nativo sin modificar" },
      { id: "TC-005", feature: "Verificar opciones del menú 'Planear' en español", precondition: "Interfaz en es-ES. Home cargada.", result: "Todas las opciones del menú están en español, sin texto en inglés.", status: "fail", bug: "BUG-004",
        steps: ["Abrir home en español", "Clic en 'Planear' en el header", "Revisar cada opción del submenú", "Identificar texto en otro idioma"], testData: "Idioma es-ES / Chrome" },
      { id: "TC-006", feature: "Seleccionar destino en buscador y verificar jerarquía de opciones", precondition: "Home cargada. Buscador visible. Origen: Barcelona-El Prat.", result: "El selector guía claramente al usuario y los países deshabilitados tienen explicación visible.", status: "fail", bug: "BUG-005",
        steps: ["Clic en campo 'Destino'", "Observar selector desplegado", "Identificar países en gris", "Intentar clic en un país gris", "Verificar mensaje explicativo"], testData: "Chrome / Origen Barcelona-El Prat" },
      { id: "TC-007", feature: "Verificar jerarquía de headings y landmark en home, resultados y checkout", precondition: "Chrome. DevTools + extensión de análisis de headers.", result: "1 H1 por página, jerarquía lógica sin saltos, <main> presente en cada página.", status: "fail", bug: "BUG-006 / BUG-007 / BUG-009",
        steps: ["Abrir home → activar extensión headers → anotar conteo H1-H6", "Ejecutar Axe → filtrar 'landmark'", "Repetir en resultados", "Repetir en checkout paso 1"], testData: "Chrome / Extensión SEO Meta in 1 Click / Axe DevTools" },
      { id: "TC-008", feature: "Verificar idioma del video de asistencia especial", precondition: "Interfaz en es-ES. Sección asistencia especial accesible.", result: "El video se muestra en español, con texto superpuesto y subtítulos en español.", status: "fail", bug: "BUG-008",
        steps: ["Navegar a Asistencia especial", "Localizar el video 'Reservar asistencia especial'", "Reproducir el video", "Observar idioma"], testData: "Idioma es-ES / Chrome" },
      { id: "TC-009", feature: "Validar texto alternativo en imágenes y banners de home", precondition: "Chrome. Axe DevTools instalado. Home cargada.", result: "Imágenes informativas con alt descriptivo, banners con información expuesta como texto accesible.", status: "fail", bug: "BUG-003",
        steps: ["Ejecutar Axe DevTools → filtrar 'image-alt'", "Inspeccionar banner principal", "Verificar atributo alt en imágenes", "Verificar si el texto del banner está en el DOM"], testData: "Chrome / Axe DevTools / DevTools Inspector" },
      { id: "TC-010", feature: "Verificar carga de la home", precondition: "Chrome. Conexión activa. Sin sesión.", result: "Logo, buscador y menú visibles y funcionales sin errores bloqueantes.", status: "pass", bug: null,
        steps: ["Abrir ryanair.com/es/es", "Esperar carga completa", "Verificar logo, buscador y menú visibles", "Verificar que el menú responde al clic"], testData: "Chrome / Conexión normal / Sin sesión" },
      { id: "TC-011", feature: "Verificar selector de fechas del buscador", precondition: "Home cargada. Buscador visible.", result: "Calendario funcional con fechas de ida y vuelta seleccionables.", status: "pass", bug: null,
        steps: ["Clic en campo de fecha", "Verificar apertura del calendario", "Seleccionar fecha de ida", "Seleccionar fecha de vuelta", "Verificar ambas fechas en campos"], testData: "Chrome / Fechas futuras (>7 días)" },
      { id: "TC-012", feature: "Verificar resultados de búsqueda de vuelos", precondition: "Origen, destino y fechas seleccionados.", result: "Vuelos disponibles con precios y filtros funcionales.", status: "pass", bug: null,
        steps: ["Completar buscador: Madrid → Londres", "Clic en 'Buscar'", "Verificar carga de resultados", "Verificar precios visibles", "Verificar que los filtros responden"], testData: "Chrome / Ruta MAD → LGW" },
      { id: "TC-013", feature: "Verificar despliegue del menú principal", precondition: "Home cargada. Menú visible en header.", result: "Menú 'Planear' se despliega con ítems navegables y funcionales.", status: "pass", bug: null,
        steps: ["Clic en 'Planear'", "Verificar que el submenú se despliega", "Clic en un ítem", "Verificar navegación correcta"], testData: "Chrome / Idioma es-ES" }
    ],
    bugsDescription: "Se identificaron 12 incidencias de accesibilidad y usabilidad durante la auditoría.",
    bugs: [
      { id: "BUG-001", title: "34 incidencias de accesibilidad detectadas en home", severity: "High", type: "Accesibilidad", testCaseId: "TS-001 / TC-001",
        steps: ["Abrir ryanair.com/es/es en Chrome", "Abrir Axe DevTools → Visión general", "Clic en 'Volver a ejecutar el escaneo'", "Revisar panel de resultados"],
        expected: "0 incidencias automáticas bajo WCAG 2.1 AA.", actual: "Axe detecta 34 incidencias: 9 graves, 24 moderadas, 1 leve.", evidence: "../../img/ryanair/BUG-001-incidencias-home.png" },
      { id: "BUG-002", title: "Links no distinguibles sin depender del color", severity: "High", type: "Accesibilidad", testCaseId: "TS-001 / TC-003",
        steps: ["Ejecutar Axe DevTools en home", "Expandir incidencia de contraste de enlaces", "Identificar el elemento afectado", "Verificar visualmente el indicador"],
        expected: "Los enlaces se diferencian del texto mediante subrayado u otro indicador (WCAG 2.1 SC 1.4.1).", actual: "Al menos un enlace solo se diferencia por el color.", evidence: "../../img/ryanair/BUG-001-incidencias-home.png" },
      { id: "BUG-003", title: "Banners con texto informativo embebido en imagen sin alternativa accesible", severity: "High", type: "Accesibilidad", testCaseId: "TS-001 / TC-009",
        steps: ["Abrir ryanair.com/es/es", "Visualizar el banner principal rotativo", "Observar el texto dentro de las imágenes", "Inspeccionar si el texto existe en el DOM"],
        expected: "La información del banner está disponible como texto en el DOM o alt descriptivo.", actual: "El banner muestra texto promocional embebido en imagen sin alternativa accesible.", evidence: "../../img/ryanair/BUG-003-home-banners.png" },
      { id: "BUG-004", title: "'Try Somewhere New' y 'Travel Agent Direct' en inglés en menú en español", severity: "Medium", type: "Localización", testCaseId: "TS-008 / TC-005",
        steps: ["Abrir ryanair.com/es/es en español", "Clic en 'Planear'", "Revisar submenú 'EXPLORAR'", "Localizar ítems en inglés"],
        expected: "Todos los ítems del menú están traducidos al español.", actual: "Dos ítems aparecen en inglés dentro del submenú en español.", evidence: "../../img/ryanair/BUG-004-home-menu-en.png" },
      { id: "BUG-005", title: "Países deshabilitados en selector de destino sin explicación visible", severity: "High", type: "Usabilidad", testCaseId: "TS-009 / TC-006",
        steps: ["Clic en campo 'Destino'", "Observar la lista de países", "Identificar países en gris claro", "Intentar clic en un país gris", "Verificar mensaje explicativo"],
        expected: "Los países sin vuelos están señalizados con un mensaje o tooltip.", actual: "10+ países deshabilitados sin ningún mensaje ni indicación.", evidence: "../../img/ryanair/BUG-005-home-seleccionar-destino.png" },
      { id: "BUG-006", title: "Documento sin landmark principal <main> definido", severity: "Medium", type: "Estructura", testCaseId: "TS-006 / TC-007",
        steps: ["Ejecutar Axe DevTools en home", "Localizar incidencia de landmark principal", "Inspeccionar HTML buscando <main> o role='main'"],
        expected: "El documento tiene exactamente un elemento <main>.", actual: "El documento no define una región principal.", evidence: "../../img/ryanair/BUG-001-incidencias-home.png" },
      { id: "BUG-007", title: "Home con 4 elementos H1 — jerarquía de headings incorrecta", severity: "High", type: "Estructura", testCaseId: "TS-006 / TC-007",
        steps: ["Abrir ryanair.com/es/es", "Activar extensión de análisis de headers", "Ir a pestaña 'HEADERS'", "Revisar conteo y lista de headings"],
        expected: "Exactamente 1 H1 por página, jerarquía lógica y continua.", actual: "La home contiene 4 elementos H1.", evidence: "../../img/ryanair/BUG-007-home-headers.png" },
      { id: "BUG-008", title: "Video de asistencia especial en catalán con interfaz en español", severity: "Medium", type: "Localización", testCaseId: "TS-007 / TC-008",
        steps: ["Navegar a Asistencia especial del Centro de ayuda", "Localizar el video 'Reservar asistencia especial'", "Reproducir el video", "Observar idioma del texto y subtítulos"],
        expected: "El video se muestra en español con la interfaz en es-ES.", actual: "El video se muestra íntegramente en catalán.", evidence: "../../img/ryanair/BUG-008-soporte-ryanair-ES.png" },
      { id: "BUG-009", title: "Checkout sin H1 ni H2 — jerarquía comienza en H3", severity: "High", type: "Estructura", testCaseId: "TS-006 / TC-007",
        steps: ["Ejecutar búsqueda y seleccionar vuelo", "Acceder al checkout", "Activar extensión de análisis de headers", "Revisar pestaña 'HEADERS'"],
        expected: "Al menos 1 H1 en la página de checkout con jerarquía lógica.", actual: "Checkout sin ningún H1 ni H2; la jerarquía comienza en H3.", evidence: "../../img/ryanair/checkout-headers.png" },
      { id: "BUG-010", title: "Contraste del botón 'Buscar' requiere verificación formal", severity: "Medium", type: "Accesibilidad", testCaseId: "TS-001 / TC-003",
        steps: ["Inspeccionar botón 'Buscar' con DevTools", "Abrir Color Picker en panel Estilos", "Registrar valores RGB", "Verificar ratio en WebAIM Contrast Checker"],
        expected: "El botón cumple ratio mínimo 4.5:1 (WCAG 2.1 SC 1.4.3).", actual: "El botón tiene color RGB (217, 181, 46) — amarillo #D9B52E, requiere verificación.", evidence: "../../img/ryanair/color-ratio.png" },
      { id: "BUG-011", title: "Modal de login no responde a la tecla Escape", severity: "High", type: "Keyboard", testCaseId: "TS-005 / TC-002",
        steps: ["Ir a home de Ryanair", "Clic en 'Iniciar sesión'", "Verificar apertura del modal", "Presionar Escape", "Observar si el modal se cierra"],
        expected: "El modal se cierra al presionar Escape y el foco retorna al botón (WCAG 2.1 SC 2.4.3).", actual: "El modal permanece abierto; Escape no tiene efecto.", evidence: "" },
      { id: "BUG-012", title: "Orden de tabulación en home no sigue lógica visual", severity: "High", type: "Keyboard", testCaseId: "TS-003 / TC-004",
        steps: ["Presionar Tab desde la barra de URL", "Documentar el orden de foco", "Comparar con el orden visual de la página", "Identificar saltos o elementos omitidos"],
        expected: "El foco recorre todos los elementos en orden lógico y predecible.", actual: "El orden de tabulación realiza saltos no predecibles.", evidence: "" }
    ],
    uxImprovements: [
      "Jerarquía Visual en Home: reducir la cantidad de elementos que compiten por la atención para centrar al usuario en el buscador.",
      "Indicador de Progreso: añadir un indicador claro de pasos en el flujo de checkout para reducir la ansiedad del usuario.",
      "Mensajes de Error Específicos: en lugar de 'Datos inválidos', especificar qué campo está mal y por qué.",
      "Rediseño de Flujo de Extras: evitar 'dark patterns' que ocultan la opción de continuar sin añadir servicios.",
      "Corrección de Contraste: actualizar la paleta de colores corporativos para cumplir con estándares de accesibilidad."
    ],
    labels: {
      description: "DESCRIPCIÓN", objective: "OBJETIVO", platform: "PLATAFORMA", stats: "INCIDENCIAS DETECTADAS",
      strategy: "ESTRATEGIA DE TESTING", scenarios: "ESCENARIOS DE PRUEBA", cases: "CASOS DE PRUEBA", bugs: "BUGS ENCONTRADOS", ux: "MEJORAS DE UX",
      thId: "ID", thFeature: "Funcionalidad", thScenario: "Escenario", thObjective: "Objetivo", thPriority: "Prioridad", thResult: "Resultado", thStatus: "Estado",
      critical: "Crítico", pass: "Pasa", fail: "Falla", expected: "Esperado", actual: "Obtenido", evidence: "Ver evidencia", contact: "Contáctame",
      precondition: "Precondición", steps: "Pasos para reproducir", testData: "Datos de prueba"
    }
  },
  en: {
    title: "UX & Accessibility — Ryanair",
    subtitle: "UX and accessibility audit of the Ryanair website, evaluating three critical pages of the booking flow: home, flight results, and checkout process.",
    description: "UX and accessibility audit of the Ryanair website, evaluating three critical pages of the booking flow: home, flight results, and checkout process. The analysis combined heuristic evaluation based on Nielsen's 10 heuristics with automated accessibility testing using Axe DevTools under the WCAG 2.1 AA standard.",
    objective: "Identify accessibility barriers, usability issues, and improvement opportunities in the main flight booking flow, focusing on the real impact on the user.",
    platform: "Web Desktop and Mobile",
    stats: {
      title: "DETECTED INCIDENTS",
      headers: ["Page", "Total", "Critical", "Serious", "Moderate"],
      rows: [
        ["Home", "34", "0", "9", "24"],
        ["Flight Results", "20", "0", "2", "18"],
        ["Checkout - Luggage", "38", "12", "5", "21"],
        ["Total", "92", "12", "16", "63"]
      ]
    },
    strategy: [
      { name: "Heuristic Evaluation", description: "Nielsen's 10 heuristics on search, flight selection, and checkout." },
      { name: "Accessibility", description: "Axe DevTools scan (WCAG 2.1 AA) on the three critical pages of the flow." },
      { name: "Exploratory Testing", description: "Free navigation to detect behaviors not covered by automated scans." },
      { name: "Functional Testing", description: "End-to-end validation: search → flight → luggage, checking consistency." }
    ],
    scenariosDesc: "14 test scenarios were defined covering accessibility, keyboard, semantic structure, localization, usability and functionality.",
    scenarios: [
      { id: "TS-001", feature: "Accessibility", scenario: "Axe DevTools scan on home", objective: "Detect WCAG 2.1 AA issues on main page", priority: "Critical" },
      { id: "TS-002", feature: "Accessibility", scenario: "Axe DevTools scan on checkout", objective: "Detect WCAG 2.1 AA issues in payment flow", priority: "Critical" },
      { id: "TS-003", feature: "Keyboard", scenario: "Tab navigation on home", objective: "Verify focus visibility and logical tab order", priority: "Critical" },
      { id: "TS-004", feature: "Keyboard", scenario: "Tab navigation on results and checkout", objective: "Verify focus is visible and functional throughout", priority: "Critical" },
      { id: "TS-005", feature: "Keyboard", scenario: "Login modal behavior with keyboard", objective: "Verify Escape closes modal and returns focus", priority: "Critical" },
      { id: "TS-006", feature: "Structure", scenario: "Headings and landmarks on home, results and checkout", objective: "Verify H1-H6 hierarchy and <main> landmark presence", priority: "Critical" },
      { id: "TS-007", feature: "Localization", scenario: "Special assistance video language", objective: "Verify video is shown in interface language", priority: "High" },
      { id: "TS-008", feature: "Localization", scenario: "Navigation menu language", objective: "Verify full menu translation", priority: "High" },
      { id: "TS-009", feature: "Usability", scenario: "Origin and destination selection flow", objective: "Verify search engine clearly guides the user", priority: "High" },
      { id: "TS-010", feature: "Usability", scenario: "Content consistency on home", objective: "Verify no duplicate sections", priority: "Medium" },
      { id: "TS-011", feature: "Functional", scenario: "Home load and main elements", objective: "Validate logo, search engine and menu are interactive", priority: "Critical" },
      { id: "TS-012", feature: "Functional", scenario: "Flight search engine — date selection", objective: "Validate outbound and return date calendar", priority: "Critical" },
      { id: "TS-013", feature: "Functional", scenario: "Main menu — expansion and navigation", objective: "Validate 'Plan' menu expands correctly", priority: "High" },
      { id: "TS-014", feature: "Functional", scenario: "Flight search results", objective: "Validate flights with prices and filters are shown", priority: "Critical" }
    ],
    casesDesc: "Each test case is linked to its corresponding scenario. Click a row to see the full detail.",
    cases: [
      { id: "TC-001", feature: "Run Axe DevTools on home under WCAG 2.1 AA", precondition: "Updated Chrome. Axe DevTools 4.11.1 installed. Home loaded without cache.", result: "0 critical or serious issues under WCAG 2.1 AA.", status: "fail", bug: "BUG-001",
        steps: ["Open ryanair.com/en/en", "Wait for full load", "Open Axe DevTools → 'Overview'", "Click 'Rerun scan'", "Review results panel — filter by Serious and Moderate"], testData: "Chrome 120+ / Axe DevTools 4.11.1 / WCAG 2.1 AA enabled" },
      { id: "TC-002", feature: "Open login modal and close with Escape", precondition: "Chrome. Home loaded. User not logged in.", result: "Modal closes on Escape key. Focus automatically returns to trigger button (WCAG 2.1 SC 2.4.3).", status: "fail", bug: "BUG-011",
        steps: ["Go to Ryanair home", "Click 'Log in'", "Verify modal opens", "Press Escape", "Verify modal closes and focus returns"], testData: "Chrome / Session not started / Keyboard only" },
      { id: "TC-003", feature: "Validate contrast of text, buttons and links on home", precondition: "Chrome. Axe DevTools installed. Home loaded.", result: "All text meets 4.5:1 ratio. Links are distinguishable without color alone.", status: "fail", bug: "BUG-002 / BUG-010",
        steps: ["Run Axe DevTools on home", "Filter by 'color-contrast' and 'link-in-text-block'", "Identify failing elements", "Verify 'Search' button color", "Verify ratio in WebAIM Contrast Checker"], testData: "Chrome / Axe DevTools / DevTools Color Picker" },
      { id: "TC-004", feature: "Verify tab order on home", precondition: "Chrome without extensions modifying CSS. Home loaded.", result: "Focus follows logical and predictable order. Outline visible on all interactive elements.", status: "fail", bug: "BUG-012",
        steps: ["Press Tab from URL bar", "Document focus order", "Verify visible outline at each step", "Verify logical order header → search → content → footer"], testData: "Chrome / Native unmodified CSS" },
      { id: "TC-005", feature: "Verify 'Plan' menu options in Spanish", precondition: "Interface in es-ES. Home loaded.", result: "All 'Plan' menu options are in Spanish. No English text is shown.", status: "fail", bug: "BUG-004",
        steps: ["Open home in Spanish", "Click 'Planear' in header", "Review every sub-menu option", "Identify any text in another language"], testData: "Language es-ES / Chrome" },
      { id: "TC-006", feature: "Select destination in search engine and verify options hierarchy", precondition: "Home loaded. Search engine visible. Origin: Barcelona-El Prat.", result: "Selector clearly guides the user. Disabled countries have a visible explanation.", status: "fail", bug: "BUG-005",
        steps: ["Click 'Destination' field", "Observe displayed selector", "Identify greyed out countries", "Click a greyed out country", "Verify explanatory message"], testData: "Chrome / Origin Barcelona-El Prat" },
      { id: "TC-007", feature: "Verify heading hierarchy and landmark on home, results and checkout", precondition: "Chrome. DevTools + header analysis extension.", result: "1 H1 per page. Logical hierarchy without jumps. <main> element present on each page.", status: "fail", bug: "BUG-006 / BUG-007 / BUG-009",
        steps: ["Open home → activate header extension → note H1-H6 count", "Run Axe → filter 'landmark'", "Repeat on flight results page", "Repeat on checkout step 1"], testData: "Chrome / SEO Meta in 1 Click / Axe DevTools" },
      { id: "TC-008", feature: "Verify special assistance video language", precondition: "Interface in es-ES. Special assistance section accessible.", result: "Video is shown in Spanish. Overlaid text and subtitles are in Spanish.", status: "fail", bug: "BUG-008",
        steps: ["Navigate to Special assistance", "Locate 'Booking special assistance' video", "Play video", "Observe language of text and subtitles"], testData: "Language es-ES / Chrome" },
      { id: "TC-009", feature: "Validate alt text on images and banners of home", precondition: "Chrome. Axe DevTools installed. Home loaded.", result: "Informative images with descriptive alt. Banners with relevant info exposed as accessible text.", status: "fail", bug: "BUG-003",
        steps: ["Run Axe DevTools → filter by 'image-alt'", "Inspect main banner", "Verify alt attribute on images", "Verify if banner text exists in DOM"], testData: "Chrome / Axe DevTools / DevTools Inspector" },
      { id: "TC-010", feature: "Verify home load", precondition: "Chrome. Active connection. No session.", result: "Logo, search engine and menu visible and functional without blocking errors.", status: "pass", bug: null,
        steps: ["Open ryanair.com/en/en", "Wait for full load", "Verify logo, search engine and menu visible", "Verify menu responds to click"], testData: "Chrome / Normal connection / No session" },
      { id: "TC-011", feature: "Verify flight search engine date selector", precondition: "Home loaded. Search engine visible.", result: "Functional calendar. Outbound and return dates selectable and visible.", status: "pass", bug: null,
        steps: ["Click date field", "Verify calendar opens", "Select outbound date", "Select return date", "Verify both dates in fields"], testData: "Chrome / Future dates (>7 days)" },
      { id: "TC-012", feature: "Verify flight search results", precondition: "Origin, destination and dates selected.", result: "Flights available with prices. Filters functional.", status: "pass", bug: null,
        steps: ["Complete search: London → Madrid", "Click 'Search'", "Verify results load", "Verify visible prices", "Verify filters respond"], testData: "Chrome / Route STN → MAD" },
      { id: "TC-013", feature: "Verify main menu expansion", precondition: "Home loaded. Menu visible in header.", result: "'Plan' menu expands. Items navigable and functional.", status: "pass", bug: null,
        steps: ["Click 'Plan'", "Verify sub-menu expands", "Click an item", "Verify correct navigation"], testData: "Chrome / Language en-EN" }
    ],
    bugsDescription: "12 accessibility and usability issues were identified during the audit.",
    bugs: [
      { id: "BUG-001", title: "34 accessibility issues detected on home", severity: "High", type: "Accessibility", testCaseId: "TS-001 / TC-001",
        steps: ["Open ryanair.com/en/en in Chrome", "Open Axe DevTools → Overview", "Click 'Rerun scan'", "Review results panel"],
        expected: "0 automatic issues under WCAG 2.1 AA.", actual: "Axe detects 34 issues: 9 serious, 24 moderate, 1 minor.", evidence: "../../img/ryanair/BUG-001-incidencias-home.png" },
      { id: "BUG-002", title: "Links not distinguishable without color", severity: "High", type: "Accessibility", testCaseId: "TS-001 / TC-003",
        steps: ["Run Axe DevTools on home", "Expand link contrast issue", "Identify affected element", "Verify visual indicator besides color"],
        expected: "Links differ from normal text via underline or other indicator (WCAG 2.1 SC 1.4.1).", actual: "At least one link only differs by color.", evidence: "../../img/ryanair/BUG-001-incidencias-home.png" },
      { id: "BUG-003", title: "Banners with informational text embedded in image without accessible alternative", severity: "High", type: "Accessibility", testCaseId: "TS-001 / TC-009",
        steps: ["Open ryanair.com/en/en", "View main rotating banner", "Observe visible text inside images", "Inspect if text exists in DOM"],
        expected: "Banner information is available as text in DOM or descriptive alt.", actual: "Banner shows promotional text embedded in image without accessible alternative.", evidence: "../../img/ryanair/BUG-003-home-banners.png" },
      { id: "BUG-004", title: "'Try Somewhere New' and 'Travel Agent Direct' in English in Spanish menu", severity: "Medium", type: "Localization", testCaseId: "TS-008 / TC-005",
        steps: ["Open ryanair.com/es/es in Spanish", "Click 'Planear'", "Review 'EXPLORAR' sub-menu", "Locate English items"],
        expected: "All menu items translated to Spanish.", actual: "Two items appear in English within the Spanish menu.", evidence: "../../img/ryanair/BUG-004-home-menu-en.png" },
      { id: "BUG-005", title: "Greyed out countries in destination selector without visible explanation", severity: "High", type: "Usability", testCaseId: "TS-009 / TC-006",
        steps: ["Click 'Destination' field", "Observe country list", "Identify light grey countries", "Try clicking a grey country", "Verify explanatory message"],
        expected: "Countries without flights are clearly marked with a message or tooltip.", actual: "10+ countries greyed out without any message or indicator.", evidence: "../../img/ryanair/BUG-005-home-seleccionar-destino.png" },
      { id: "BUG-006", title: "Document without main landmark defined", severity: "Medium", type: "Structure", testCaseId: "TS-006 / TC-007",
        steps: ["Run Axe DevTools on home", "Locate main landmark issue", "Inspect HTML for <main> or role='main'"],
        expected: "Document has exactly one <main> element.", actual: "Document does not define a main region.", evidence: "../../img/ryanair/BUG-001-incidencias-home.png" },
      { id: "BUG-007", title: "Home with 4 H1 elements — incorrect heading hierarchy", severity: "High", type: "Structure", testCaseId: "TS-006 / TC-007",
        steps: ["Open ryanair.com/en/en", "Activate header analysis extension", "Go to 'HEADERS' tab", "Review count and heading list"],
        expected: "Exactly 1 H1 per page, logical continuous hierarchy.", actual: "Home contains 4 H1 elements.", evidence: "../../img/ryanair/BUG-007-home-headers.png" },
      { id: "BUG-008", title: "Special assistance video in Catalan with Spanish interface", severity: "Medium", type: "Localization", testCaseId: "TS-007 / TC-008",
        steps: ["Navigate to Special Assistance section", "Locate 'Booking special assistance' video", "Play video", "Observe language of text and subtitles"],
        expected: "Video shown in Spanish when interface is es-ES.", actual: "Video shown entirely in Catalan.", evidence: "../../img/ryanair/BUG-008-soporte-ryanair-ES.png" },
      { id: "BUG-009", title: "Checkout without H1 or H2 — hierarchy starts at H3", severity: "High", type: "Structure", testCaseId: "TS-006 / TC-007",
        steps: ["Run search and select flight", "Access checkout", "Activate header analysis extension", "Review 'HEADERS' tab"],
        expected: "At least 1 H1 on checkout with logical hierarchy.", actual: "Checkout without any H1 or H2; hierarchy starts at H3.", evidence: "../../img/ryanair/checkout-headers.png" },
      { id: "BUG-010", title: "'Search' button contrast requires formal verification", severity: "Medium", type: "Accessibility", testCaseId: "TS-001 / TC-003",
        steps: ["Inspect 'Search' button with DevTools", "Open Color Picker", "Record RGB values", "Verify ratio in WebAIM Contrast Checker"],
        expected: "Button meets minimum 4.5:1 ratio (WCAG 2.1 SC 1.4.3).", actual: "Button has RGB (217, 181, 46) — yellow #D9B52E, requires verification.", evidence: "../../img/ryanair/color-ratio.png" },
      { id: "BUG-011", title: "Login modal does not respond to Escape key", severity: "High", type: "Keyboard", testCaseId: "TS-005 / TC-002",
        steps: ["Go to Ryanair home", "Click 'Log in'", "Verify modal opens", "Press Escape", "Observe if modal closes"],
        expected: "Modal closes on Escape, focus returns to button (WCAG 2.1 SC 2.4.3).", actual: "Modal remains open; Escape has no effect.", evidence: "" },
      { id: "BUG-012", title: "Home tab order does not follow visual logic", severity: "High", type: "Keyboard", testCaseId: "TS-003 / TC-004",
        steps: ["Press Tab from URL bar", "Document focus order", "Compare with visual page order", "Identify jumps or skipped elements"],
        expected: "Focus cycles through elements in logical predictable order.", actual: "Tab order makes unpredictable jumps.", evidence: "" }
    ],
    uxImprovements: [
      "Visual Hierarchy on Home: reduce competing elements to focus the user on the search engine.",
      "Progress Indicator: add a clear step-by-step indicator in the checkout flow to reduce user anxiety.",
      "Specific Error Messages: instead of 'Invalid data', specify which field is wrong and why.",
      "Redesign of Extras Flow: avoid 'dark patterns' that hide the option to continue without adding services.",
      "Contrast Correction: update the corporate color palette to meet accessibility standards."
    ],
    labels: {
      description: "DESCRIPTION", objective: "OBJECTIVE", platform: "PLATFORM", stats: "DETECTED INCIDENTS",
      strategy: "TESTING STRATEGY", scenarios: "TEST SCENARIOS", cases: "TEST CASES", bugs: "BUGS FOUND", ux: "UX IMPROVEMENTS",
      thId: "ID", thFeature: "Feature", thScenario: "Scenario", thObjective: "Objective", thPriority: "Priority", thResult: "Result", thStatus: "Status",
      critical: "Critical", pass: "Pass", fail: "Fail", expected: "Expected", actual: "Actual", evidence: "View evidence", contact: "Contact me",
      precondition: "Precondition", steps: "Steps to reproduce", testData: "Test data"
    }
  }
};
